
// Code generated by stanc v2.27.0
#include <stan/model/model_header.hpp>
namespace cepheid_v3_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 36> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 34, column 2 to column 16)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 35, column 2 to column 26)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 37, column 2 to column 15)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 38, column 2 to column 25)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 41, column 2 to column 19)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 42, column 2 to column 18)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 48, column 2 to column 20)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 49, column 2 to column 20)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 52, column 2 to column 50)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 55, column 2 to column 47)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 62, column 2 to column 27)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 63, column 2 to column 26)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 64, column 2 to column 29)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 65, column 2 to column 28)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 68, column 2 to column 38)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 69, column 2 to column 35)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 72, column 2 to column 34)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 11, column 2 to column 9)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 12, column 2 to column 9)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 14, column 13 to column 15)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 14, column 2 to column 17)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 15, column 9 to column 11)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 15, column 2 to column 19)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 16, column 2 to column 15)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 17, column 9 to column 11)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 17, column 2 to column 20)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 18, column 9 to column 11)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 18, column 2 to column 15)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 24, column 9 to column 11)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 24, column 2 to column 16)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 27, column 2 to column 26)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 41, column 9 to column 11)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 42, column 9 to column 11)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 48, column 9 to column 11)",
 " (in '/Users/fran/projects/BayesianWorkflow/src/notebooks/stan/cepheid_v3.stan', line 49, column 9 to column 11)"};



class cepheid_v3_model final : public model_base_crtp<cepheid_v3_model> {

 private:
  int Ng;
  int Nt;
  std::vector<int> gal_id;
  Eigen::Matrix<double, -1, 1> m_obs__;
  double sigma_m;
  Eigen::Matrix<double, -1, 1> log10P__;
  Eigen::Matrix<double, -1, 1> z__;
  Eigen::Matrix<double, -1, 1> dL__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> m_obs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> log10P{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> z{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> dL{nullptr, 0};
 
 public:
  ~cepheid_v3_model() { }
  
  inline std::string model_name() const final { return "cepheid_v3_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.27.0", "stancflags = "};
  }
  
  
  cepheid_v3_model(stan::io::var_context& context__,
                   unsigned int random_seed__ = 0,
                   std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "cepheid_v3_model_namespace::cepheid_v3_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 18;
      context__.validate_dims("data initialization","Ng","int",
           std::vector<size_t>{});
      Ng = std::numeric_limits<int>::min();
      
      current_statement__ = 18;
      Ng = context__.vals_i("Ng")[(1 - 1)];
      current_statement__ = 19;
      context__.validate_dims("data initialization","Nt","int",
           std::vector<size_t>{});
      Nt = std::numeric_limits<int>::min();
      
      current_statement__ = 19;
      Nt = context__.vals_i("Nt")[(1 - 1)];
      current_statement__ = 20;
      validate_non_negative_index("gal_id", "Nt", Nt);
      current_statement__ = 21;
      context__.validate_dims("data initialization","gal_id","int",
           std::vector<size_t>{static_cast<size_t>(Nt)});
      gal_id = std::vector<int>(Nt, std::numeric_limits<int>::min());
      
      current_statement__ = 21;
      gal_id = context__.vals_i("gal_id");
      current_statement__ = 22;
      validate_non_negative_index("m_obs", "Nt", Nt);
      current_statement__ = 23;
      context__.validate_dims("data initialization","m_obs","double",
           std::vector<size_t>{static_cast<size_t>(Nt)});
      m_obs__ = Eigen::Matrix<double, -1, 1>(Nt);
      new (&m_obs) Eigen::Map<Eigen::Matrix<double, -1, 1>>(m_obs__.data(), Nt);
      
      
      {
        std::vector<local_scalar_t__> m_obs_flat__;
        current_statement__ = 23;
        m_obs_flat__ = context__.vals_r("m_obs");
        current_statement__ = 23;
        pos__ = 1;
        current_statement__ = 23;
        for (int sym1__ = 1; sym1__ <= Nt; ++sym1__) {
          current_statement__ = 23;
          assign(m_obs, m_obs_flat__[(pos__ - 1)],
            "assigning variable m_obs", index_uni(sym1__));
          current_statement__ = 23;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 24;
      context__.validate_dims("data initialization","sigma_m","double",
           std::vector<size_t>{});
      sigma_m = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 24;
      sigma_m = context__.vals_r("sigma_m")[(1 - 1)];
      current_statement__ = 25;
      validate_non_negative_index("log10P", "Nt", Nt);
      current_statement__ = 26;
      context__.validate_dims("data initialization","log10P","double",
           std::vector<size_t>{static_cast<size_t>(Nt)});
      log10P__ = Eigen::Matrix<double, -1, 1>(Nt);
      new (&log10P) Eigen::Map<Eigen::Matrix<double, -1, 1>>(log10P__.data(), Nt);
      
      
      {
        std::vector<local_scalar_t__> log10P_flat__;
        current_statement__ = 26;
        log10P_flat__ = context__.vals_r("log10P");
        current_statement__ = 26;
        pos__ = 1;
        current_statement__ = 26;
        for (int sym1__ = 1; sym1__ <= Nt; ++sym1__) {
          current_statement__ = 26;
          assign(log10P, log10P_flat__[(pos__ - 1)],
            "assigning variable log10P", index_uni(sym1__));
          current_statement__ = 26;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 27;
      validate_non_negative_index("z", "Ng", Ng);
      current_statement__ = 28;
      context__.validate_dims("data initialization","z","double",
           std::vector<size_t>{static_cast<size_t>(Ng)});
      z__ = Eigen::Matrix<double, -1, 1>(Ng);
      new (&z) Eigen::Map<Eigen::Matrix<double, -1, 1>>(z__.data(), Ng);
      
      {
        std::vector<local_scalar_t__> z_flat__;
        current_statement__ = 28;
        z_flat__ = context__.vals_r("z");
        current_statement__ = 28;
        pos__ = 1;
        current_statement__ = 28;
        for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
          current_statement__ = 28;
          assign(z, z_flat__[(pos__ - 1)],
            "assigning variable z", index_uni(sym1__));
          current_statement__ = 28;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 29;
      validate_non_negative_index("dL", "Ng", Ng);
      current_statement__ = 30;
      dL__ = Eigen::Matrix<double, -1, 1>(Ng);
      new (&dL) Eigen::Map<Eigen::Matrix<double, -1, 1>>(dL__.data(), Ng);
      stan::math::fill(dL, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 31;
      assign(dL, divide(multiply(3.0e5, z), 70.0), "assigning variable dL");
      current_statement__ = 32;
      validate_non_negative_index("alpha", "Ng", Ng);
      current_statement__ = 33;
      validate_non_negative_index("beta", "Ng", Ng);
      current_statement__ = 34;
      validate_non_negative_index("M_true", "Nt", Nt);
      current_statement__ = 35;
      validate_non_negative_index("m_true", "Nt", Nt);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 1 + 1 + 1 + 1 + Ng + Ng;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "cepheid_v3_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ mu_alpha;
      mu_alpha = DUMMY_VAR__;
      
      current_statement__ = 1;
      mu_alpha = in__.template read<local_scalar_t__>();
      local_scalar_t__ tau_alpha;
      tau_alpha = DUMMY_VAR__;
      
      current_statement__ = 2;
      tau_alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                    0, lp__);
      local_scalar_t__ mu_beta;
      mu_beta = DUMMY_VAR__;
      
      current_statement__ = 3;
      mu_beta = in__.template read<local_scalar_t__>();
      local_scalar_t__ tau_beta;
      tau_beta = DUMMY_VAR__;
      
      current_statement__ = 4;
      tau_beta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                   0, lp__);
      Eigen::Matrix<local_scalar_t__, -1, 1> alpha;
      alpha = Eigen::Matrix<local_scalar_t__, -1, 1>(Ng);
      stan::math::fill(alpha, DUMMY_VAR__);
      
      current_statement__ = 5;
      alpha = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(Ng);
      Eigen::Matrix<local_scalar_t__, -1, 1> beta;
      beta = Eigen::Matrix<local_scalar_t__, -1, 1>(Ng);
      stan::math::fill(beta, DUMMY_VAR__);
      
      current_statement__ = 6;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(Ng);
      Eigen::Matrix<local_scalar_t__, -1, 1> M_true;
      M_true = Eigen::Matrix<local_scalar_t__, -1, 1>(Nt);
      stan::math::fill(M_true, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> m_true;
      m_true = Eigen::Matrix<local_scalar_t__, -1, 1>(Nt);
      stan::math::fill(m_true, DUMMY_VAR__);
      
      current_statement__ = 9;
      assign(M_true,
        add(rvalue(alpha, "alpha", index_multi(gal_id)),
          elt_multiply(rvalue(beta, "beta", index_multi(gal_id)), log10P)),
        "assigning variable M_true");
      current_statement__ = 10;
      assign(m_true,
        add(
          add(M_true,
            multiply(5,
              stan::math::log10(rvalue(dL, "dL", index_multi(gal_id))))), 25),
        "assigning variable m_true");
      {
        current_statement__ = 11;
        lp_accum__.add(normal_lpdf<propto__>(mu_alpha, 0, 10));
        current_statement__ = 12;
        lp_accum__.add(normal_lpdf<propto__>(mu_beta, -5, 5));
        current_statement__ = 13;
        lp_accum__.add(cauchy_lpdf<propto__>(tau_alpha, 0, 2.5));
        current_statement__ = 14;
        lp_accum__.add(cauchy_lpdf<propto__>(tau_beta, 0, 2.5));
        current_statement__ = 15;
        lp_accum__.add(normal_lpdf<propto__>(alpha, mu_alpha, tau_alpha));
        current_statement__ = 16;
        lp_accum__.add(normal_lpdf<propto__>(beta, mu_beta, tau_beta));
        current_statement__ = 17;
        lp_accum__.add(normal_lpdf<propto__>(m_obs, m_true, sigma_m));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "cepheid_v3_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double mu_alpha;
      mu_alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      mu_alpha = in__.template read<local_scalar_t__>();
      double tau_alpha;
      tau_alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      tau_alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                    0, lp__);
      double mu_beta;
      mu_beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu_beta = in__.template read<local_scalar_t__>();
      double tau_beta;
      tau_beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      tau_beta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                   0, lp__);
      Eigen::Matrix<double, -1, 1> alpha;
      alpha = Eigen::Matrix<double, -1, 1>(Ng);
      stan::math::fill(alpha, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      alpha = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(Ng);
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(Ng);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 6;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(Ng);
      Eigen::Matrix<double, -1, 1> M_true;
      M_true = Eigen::Matrix<double, -1, 1>(Nt);
      stan::math::fill(M_true, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> m_true;
      m_true = Eigen::Matrix<double, -1, 1>(Nt);
      stan::math::fill(m_true, std::numeric_limits<double>::quiet_NaN());
      
      vars__.emplace_back(mu_alpha);
      vars__.emplace_back(tau_alpha);
      vars__.emplace_back(mu_beta);
      vars__.emplace_back(tau_beta);
      for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
        vars__.emplace_back(alpha[(sym1__ - 1)]);
      }
      for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);
      }
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 9;
      assign(M_true,
        add(rvalue(alpha, "alpha", index_multi(gal_id)),
          elt_multiply(rvalue(beta, "beta", index_multi(gal_id)), log10P)),
        "assigning variable M_true");
      current_statement__ = 10;
      assign(m_true,
        add(
          add(M_true,
            multiply(5,
              stan::math::log10(rvalue(dL, "dL", index_multi(gal_id))))), 25),
        "assigning variable m_true");
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= Nt; ++sym1__) {
          vars__.emplace_back(M_true[(sym1__ - 1)]);
        }
        for (int sym1__ = 1; sym1__ <= Nt; ++sym1__) {
          vars__.emplace_back(m_true[(sym1__ - 1)]);
        }
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    int current_statement__ = 0; 
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double mu_alpha;
      mu_alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      mu_alpha = context__.vals_r("mu_alpha")[(1 - 1)];
      double tau_alpha;
      tau_alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      tau_alpha = context__.vals_r("tau_alpha")[(1 - 1)];
      double tau_alpha_free__;
      tau_alpha_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      tau_alpha_free__ = stan::math::lb_free(tau_alpha, 0);
      double mu_beta;
      mu_beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu_beta = context__.vals_r("mu_beta")[(1 - 1)];
      double tau_beta;
      tau_beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      tau_beta = context__.vals_r("tau_beta")[(1 - 1)];
      double tau_beta_free__;
      tau_beta_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      tau_beta_free__ = stan::math::lb_free(tau_beta, 0);
      Eigen::Matrix<double, -1, 1> alpha;
      alpha = Eigen::Matrix<double, -1, 1>(Ng);
      stan::math::fill(alpha, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 5;
        alpha_flat__ = context__.vals_r("alpha");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
          current_statement__ = 5;
          assign(alpha, alpha_flat__[(pos__ - 1)],
            "assigning variable alpha", index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(Ng);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 6;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
          current_statement__ = 6;
          assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", index_uni(sym1__));
          current_statement__ = 6;
          pos__ = (pos__ + 1);
        }
      }
      vars__.emplace_back(mu_alpha);
      vars__.emplace_back(tau_alpha_free__);
      vars__.emplace_back(mu_beta);
      vars__.emplace_back(tau_beta_free__);
      for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
        vars__.emplace_back(alpha[(sym1__ - 1)]);
      }
      for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"mu_alpha", "tau_alpha", "mu_beta",
      "tau_beta", "alpha", "beta", "M_true", "m_true"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{static_cast<size_t>(Ng)},
      std::vector<size_t>{static_cast<size_t>(Ng)},
      std::vector<size_t>{static_cast<size_t>(Nt)},
      std::vector<size_t>{static_cast<size_t>(Nt)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "mu_alpha");
    param_names__.emplace_back(std::string() + "tau_alpha");
    param_names__.emplace_back(std::string() + "mu_beta");
    param_names__.emplace_back(std::string() + "tau_beta");
    for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= Nt; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "M_true" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= Nt; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "m_true" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "mu_alpha");
    param_names__.emplace_back(std::string() + "tau_alpha");
    param_names__.emplace_back(std::string() + "mu_beta");
    param_names__.emplace_back(std::string() + "tau_beta");
    for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= Ng; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= Nt; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "M_true" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= Nt; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "m_true" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"mu_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Ng) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Ng) + "},\"block\":\"parameters\"},{\"name\":\"M_true\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Nt) + "},\"block\":\"transformed_parameters\"},{\"name\":\"m_true\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Nt) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"mu_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau_beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Ng) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Ng) + "},\"block\":\"parameters\"},{\"name\":\"M_true\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Nt) + "},\"block\":\"transformed_parameters\"},{\"name\":\"m_true\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Nt) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec;
      vars_vec.reserve(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars,
       emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec;
      params_r_vec.reserve(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }

};
}
using stan_model = cepheid_v3_model_namespace::cepheid_v3_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return cepheid_v3_model_namespace::profiles__;
}

#endif


