name: Pages
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        sudo apt-get install -y pandoc
        pip install markupsafe==2.0.1
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        documentation_path: src
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages

